### ISSUE TITLE
Any updates for beta release?

### ISSUE THREAD

**Issue by chocovish** [typetron/typetron#1]
I have been looking for a typescript mvc framework. found typetron and nest.js. I find the coding pattern of typetron is more attractive. any updates on that? seems the last commit was 7 months ago. 🙄

**Comment by IonelLupu** [comment]
Hey @chocovish . Yes. I have some updates on Typetron. I usually post updates about it on my Twitter channel [@ionelLupu_](https://twitter.com/ionelLupu_) (maybe I need to start posting updates on github here as well)

Most of the work in the past months was done on the framework internals itself in the [typetron/framework](https://github.com/typetron/framework) repository (since I need to build so many modules from scratch to preserve the performance of the framework).

I am working right now at the documentation of the Beta release alongside with the tutorial for the [Twitter clone app here](https://typetron.org/tutorials) (the second tutorial)

I hope I can release the Beta version by the end of the year and after that I can start working towards the V1 release. The V1 release will be marked the the third tutorial: "Building an admin dashboard with Typetron". It will have a lot of cool features that will also include frontend libraries(for vanilla JS, Angular, React, Vue) to help you build full-stack apps as fast as possible with the least amount of code as possible. 

Stay tuned! I will try updating Github a lot more often

**Comment by IonelLupu** [comment]
@chocovish Beta version was just release a few days ago.

You can check the post here: https://dev.to/typetron/tyeptron-beta-is-here-typetron-org-5g16

You can also check the second tutorial that marks the Beta release here: https://typetron.org/tutorials/twitter-clone/
